chore: resolve folder about report mochasome

diff --git a/.github/workflows/mochawesome-ui.yml b/.github/workflows/mochawesome-ui.yml
--- a/.github/workflows/mochawesome-ui.yml
+++ b/.github/workflows/mochawesome-ui.yml
@@ -17,7 +17,7 @@ permissions:
   contents: write
 
 jobs:
-  ui-tests:
+  api-tests:
     runs-on: ubuntu-latest
 
     steps:
@@ -33,14 +33,33 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run UI tests
-        run: BROWSER=${{ github.event.inputs.browser }} npm run test:ui-mochawesome
+      - name: Run API tests with Mochawesome
+        run: |
+          if [ "${{ github.event.inputs.test_type }}" == "api" ]; then
+            npm run test:api-mochawesome
+          else
+            echo "Unknown test type selected"
+            exit 1
+          fi
 
       - name: Merge Mochawesome reports
         run: npm run mochawesome:merge
 
       - name: Generate Mochawesome report
         run: npm run mochawesome:generate
+
+      - name: List files in mochawesome-report
+        run: ls -R mochawesome-report
+
+      - name: List files in root
+        run: ls -R .
+
+      - name: Check for merged.html
+        run: |
+          if [ ! -f merged.html ]; then
+            echo "merged.html not found!"
+            exit 1
+          fi
 
       - name: Load test report history
         uses: actions/checkout@v3
@@ -56,6 +75,9 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
-          publish_dir: mochawesome-report
+          publish_dir: .
           allow_empty_commit: true
           force_orphan: true
+
+      - name: Wait for GitHub Pages to update
+        run: sleep 10
